/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WidgetRouteImport } from './routes/widget'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as NoAccessRouteImport } from './routes/no-access'
import { Route as MfaRouteImport } from './routes/mfa'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWebsitesRouteImport } from './routes/_authenticated/websites'
import { Route as AuthenticatedTrainingRouteImport } from './routes/_authenticated/training'
import { Route as AuthenticatedStaffRouteImport } from './routes/_authenticated/staff'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSecurityRouteImport } from './routes/_authenticated/security'
import { Route as AuthenticatedRoutingRouteImport } from './routes/_authenticated/routing'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedQualityRouteImport } from './routes/_authenticated/quality'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedOrganizationsRouteImport } from './routes/_authenticated/organizations'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedKnowledgeRouteImport } from './routes/_authenticated/knowledge'
import { Route as AuthenticatedIntakeRouteImport } from './routes/_authenticated/intake'
import { Route as AuthenticatedInboxRouteImport } from './routes/_authenticated/inbox'
import { Route as AuthenticatedDepartmentsRouteImport } from './routes/_authenticated/departments'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedContactsRouteImport } from './routes/_authenticated/contacts'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedAiConsoleRouteImport } from './routes/_authenticated/ai-console'
import { Route as ApiPublicWidgetDotjsRouteImport } from './routes/api/public/widget[.]js'
import { Route as ApiPublicTmpSeedTestAccountsRouteImport } from './routes/api/public/tmp-seed-test-accounts'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as ApiPublicStaffAvatarSplatRouteImport } from './routes/api/public/staff-avatar/$'
import { Route as ApiPublicHooksSlaCheckRouteImport } from './routes/api/public/hooks/sla-check'
import { Route as ApiPublicChatUploadRouteImport } from './routes/api/public/chat/upload'
import { Route as ApiPublicChatSessionRouteImport } from './routes/api/public/chat/session'
import { Route as ApiPublicChatRateRouteImport } from './routes/api/public/chat/rate'
import { Route as ApiPublicChatPollRouteImport } from './routes/api/public/chat/poll'
import { Route as ApiPublicChatMessageRouteImport } from './routes/api/public/chat/message'
import { Route as ApiPublicChatFeedbackRouteImport } from './routes/api/public/chat/feedback'
import { Route as ApiPublicChatEscalateRouteImport } from './routes/api/public/chat/escalate'
import { Route as ApiPublicChatConfigRouteImport } from './routes/api/public/chat/config'
import { Route as ApiPublicBrandingSplatRouteImport } from './routes/api/public/branding/$'

const WidgetRoute = WidgetRouteImport.update({
  id: '/widget',
  path: '/widget',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const NoAccessRoute = NoAccessRouteImport.update({
  id: '/no-access',
  path: '/no-access',
  getParentRoute: () => rootRouteImport,
} as any)
const MfaRoute = MfaRouteImport.update({
  id: '/mfa',
  path: '/mfa',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWebsitesRoute = AuthenticatedWebsitesRouteImport.update({
  id: '/websites',
  path: '/websites',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrainingRoute = AuthenticatedTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStaffRoute = AuthenticatedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSecurityRoute = AuthenticatedSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRoutingRoute = AuthenticatedRoutingRouteImport.update({
  id: '/routing',
  path: '/routing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQualityRoute = AuthenticatedQualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrganizationsRoute =
  AuthenticatedOrganizationsRouteImport.update({
    id: '/organizations',
    path: '/organizations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKnowledgeRoute = AuthenticatedKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntakeRoute = AuthenticatedIntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInboxRoute = AuthenticatedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDepartmentsRoute =
  AuthenticatedDepartmentsRouteImport.update({
    id: '/departments',
    path: '/departments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContactsRoute = AuthenticatedContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiConsoleRoute = AuthenticatedAiConsoleRouteImport.update({
  id: '/ai-console',
  path: '/ai-console',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicWidgetDotjsRoute = ApiPublicWidgetDotjsRouteImport.update({
  id: '/api/public/widget.js',
  path: '/api/public/widget.js',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTmpSeedTestAccountsRoute =
  ApiPublicTmpSeedTestAccountsRouteImport.update({
    id: '/api/public/tmp-seed-test-accounts',
    path: '/api/public/tmp-seed-test-accounts',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicStaffAvatarSplatRoute =
  ApiPublicStaffAvatarSplatRouteImport.update({
    id: '/api/public/staff-avatar/$',
    path: '/api/public/staff-avatar/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSlaCheckRoute = ApiPublicHooksSlaCheckRouteImport.update({
  id: '/api/public/hooks/sla-check',
  path: '/api/public/hooks/sla-check',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicChatUploadRoute = ApiPublicChatUploadRouteImport.update({
  id: '/api/public/chat/upload',
  path: '/api/public/chat/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicChatSessionRoute = ApiPublicChatSessionRouteImport.update({
  id: '/api/public/chat/session',
  path: '/api/public/chat/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicChatRateRoute = ApiPublicChatRateRouteImport.update({
  id: '/api/public/chat/rate',
  path: '/api/public/chat/rate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicChatPollRoute = ApiPublicChatPollRouteImport.update({
  id: '/api/public/chat/poll',
  path: '/api/public/chat/poll',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicChatMessageRoute = ApiPublicChatMessageRouteImport.update({
  id: '/api/public/chat/message',
  path: '/api/public/chat/message',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicChatFeedbackRoute = ApiPublicChatFeedbackRouteImport.update({
  id: '/api/public/chat/feedback',
  path: '/api/public/chat/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicChatEscalateRoute = ApiPublicChatEscalateRouteImport.update({
  id: '/api/public/chat/escalate',
  path: '/api/public/chat/escalate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicChatConfigRoute = ApiPublicChatConfigRouteImport.update({
  id: '/api/public/chat/config',
  path: '/api/public/chat/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBrandingSplatRoute = ApiPublicBrandingSplatRouteImport.update({
  id: '/api/public/branding/$',
  path: '/api/public/branding/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/invite': typeof InviteRoute
  '/mfa': typeof MfaRoute
  '/no-access': typeof NoAccessRoute
  '/reset-password': typeof ResetPasswordRoute
  '/widget': typeof WidgetRoute
  '/ai-console': typeof AuthenticatedAiConsoleRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/departments': typeof AuthenticatedDepartmentsRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/intake': typeof AuthenticatedIntakeRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/organizations': typeof AuthenticatedOrganizationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/quality': typeof AuthenticatedQualityRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/routing': typeof AuthenticatedRoutingRoute
  '/security': typeof AuthenticatedSecurityRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/training': typeof AuthenticatedTrainingRoute
  '/websites': typeof AuthenticatedWebsitesRoute
  '/api/public/tmp-seed-test-accounts': typeof ApiPublicTmpSeedTestAccountsRoute
  '/api/public/widget.js': typeof ApiPublicWidgetDotjsRoute
  '/api/public/branding/$': typeof ApiPublicBrandingSplatRoute
  '/api/public/chat/config': typeof ApiPublicChatConfigRoute
  '/api/public/chat/escalate': typeof ApiPublicChatEscalateRoute
  '/api/public/chat/feedback': typeof ApiPublicChatFeedbackRoute
  '/api/public/chat/message': typeof ApiPublicChatMessageRoute
  '/api/public/chat/poll': typeof ApiPublicChatPollRoute
  '/api/public/chat/rate': typeof ApiPublicChatRateRoute
  '/api/public/chat/session': typeof ApiPublicChatSessionRoute
  '/api/public/chat/upload': typeof ApiPublicChatUploadRoute
  '/api/public/hooks/sla-check': typeof ApiPublicHooksSlaCheckRoute
  '/api/public/staff-avatar/$': typeof ApiPublicStaffAvatarSplatRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/invite': typeof InviteRoute
  '/mfa': typeof MfaRoute
  '/no-access': typeof NoAccessRoute
  '/reset-password': typeof ResetPasswordRoute
  '/widget': typeof WidgetRoute
  '/ai-console': typeof AuthenticatedAiConsoleRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/departments': typeof AuthenticatedDepartmentsRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/intake': typeof AuthenticatedIntakeRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/organizations': typeof AuthenticatedOrganizationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/quality': typeof AuthenticatedQualityRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/routing': typeof AuthenticatedRoutingRoute
  '/security': typeof AuthenticatedSecurityRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/training': typeof AuthenticatedTrainingRoute
  '/websites': typeof AuthenticatedWebsitesRoute
  '/api/public/tmp-seed-test-accounts': typeof ApiPublicTmpSeedTestAccountsRoute
  '/api/public/widget.js': typeof ApiPublicWidgetDotjsRoute
  '/api/public/branding/$': typeof ApiPublicBrandingSplatRoute
  '/api/public/chat/config': typeof ApiPublicChatConfigRoute
  '/api/public/chat/escalate': typeof ApiPublicChatEscalateRoute
  '/api/public/chat/feedback': typeof ApiPublicChatFeedbackRoute
  '/api/public/chat/message': typeof ApiPublicChatMessageRoute
  '/api/public/chat/poll': typeof ApiPublicChatPollRoute
  '/api/public/chat/rate': typeof ApiPublicChatRateRoute
  '/api/public/chat/session': typeof ApiPublicChatSessionRoute
  '/api/public/chat/upload': typeof ApiPublicChatUploadRoute
  '/api/public/hooks/sla-check': typeof ApiPublicHooksSlaCheckRoute
  '/api/public/staff-avatar/$': typeof ApiPublicStaffAvatarSplatRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/invite': typeof InviteRoute
  '/mfa': typeof MfaRoute
  '/no-access': typeof NoAccessRoute
  '/reset-password': typeof ResetPasswordRoute
  '/widget': typeof WidgetRoute
  '/_authenticated/ai-console': typeof AuthenticatedAiConsoleRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/contacts': typeof AuthenticatedContactsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/departments': typeof AuthenticatedDepartmentsRoute
  '/_authenticated/inbox': typeof AuthenticatedInboxRoute
  '/_authenticated/intake': typeof AuthenticatedIntakeRoute
  '/_authenticated/knowledge': typeof AuthenticatedKnowledgeRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/organizations': typeof AuthenticatedOrganizationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/quality': typeof AuthenticatedQualityRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/routing': typeof AuthenticatedRoutingRoute
  '/_authenticated/security': typeof AuthenticatedSecurityRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/staff': typeof AuthenticatedStaffRoute
  '/_authenticated/training': typeof AuthenticatedTrainingRoute
  '/_authenticated/websites': typeof AuthenticatedWebsitesRoute
  '/api/public/tmp-seed-test-accounts': typeof ApiPublicTmpSeedTestAccountsRoute
  '/api/public/widget.js': typeof ApiPublicWidgetDotjsRoute
  '/api/public/branding/$': typeof ApiPublicBrandingSplatRoute
  '/api/public/chat/config': typeof ApiPublicChatConfigRoute
  '/api/public/chat/escalate': typeof ApiPublicChatEscalateRoute
  '/api/public/chat/feedback': typeof ApiPublicChatFeedbackRoute
  '/api/public/chat/message': typeof ApiPublicChatMessageRoute
  '/api/public/chat/poll': typeof ApiPublicChatPollRoute
  '/api/public/chat/rate': typeof ApiPublicChatRateRoute
  '/api/public/chat/session': typeof ApiPublicChatSessionRoute
  '/api/public/chat/upload': typeof ApiPublicChatUploadRoute
  '/api/public/hooks/sla-check': typeof ApiPublicHooksSlaCheckRoute
  '/api/public/staff-avatar/$': typeof ApiPublicStaffAvatarSplatRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/invite'
    | '/mfa'
    | '/no-access'
    | '/reset-password'
    | '/widget'
    | '/ai-console'
    | '/audit'
    | '/contacts'
    | '/dashboard'
    | '/departments'
    | '/inbox'
    | '/intake'
    | '/knowledge'
    | '/notifications'
    | '/organizations'
    | '/profile'
    | '/quality'
    | '/reports'
    | '/routing'
    | '/security'
    | '/settings'
    | '/staff'
    | '/training'
    | '/websites'
    | '/api/public/tmp-seed-test-accounts'
    | '/api/public/widget.js'
    | '/api/public/branding/$'
    | '/api/public/chat/config'
    | '/api/public/chat/escalate'
    | '/api/public/chat/feedback'
    | '/api/public/chat/message'
    | '/api/public/chat/poll'
    | '/api/public/chat/rate'
    | '/api/public/chat/session'
    | '/api/public/chat/upload'
    | '/api/public/hooks/sla-check'
    | '/api/public/staff-avatar/$'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/invite'
    | '/mfa'
    | '/no-access'
    | '/reset-password'
    | '/widget'
    | '/ai-console'
    | '/audit'
    | '/contacts'
    | '/dashboard'
    | '/departments'
    | '/inbox'
    | '/intake'
    | '/knowledge'
    | '/notifications'
    | '/organizations'
    | '/profile'
    | '/quality'
    | '/reports'
    | '/routing'
    | '/security'
    | '/settings'
    | '/staff'
    | '/training'
    | '/websites'
    | '/api/public/tmp-seed-test-accounts'
    | '/api/public/widget.js'
    | '/api/public/branding/$'
    | '/api/public/chat/config'
    | '/api/public/chat/escalate'
    | '/api/public/chat/feedback'
    | '/api/public/chat/message'
    | '/api/public/chat/poll'
    | '/api/public/chat/rate'
    | '/api/public/chat/session'
    | '/api/public/chat/upload'
    | '/api/public/hooks/sla-check'
    | '/api/public/staff-avatar/$'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/invite'
    | '/mfa'
    | '/no-access'
    | '/reset-password'
    | '/widget'
    | '/_authenticated/ai-console'
    | '/_authenticated/audit'
    | '/_authenticated/contacts'
    | '/_authenticated/dashboard'
    | '/_authenticated/departments'
    | '/_authenticated/inbox'
    | '/_authenticated/intake'
    | '/_authenticated/knowledge'
    | '/_authenticated/notifications'
    | '/_authenticated/organizations'
    | '/_authenticated/profile'
    | '/_authenticated/quality'
    | '/_authenticated/reports'
    | '/_authenticated/routing'
    | '/_authenticated/security'
    | '/_authenticated/settings'
    | '/_authenticated/staff'
    | '/_authenticated/training'
    | '/_authenticated/websites'
    | '/api/public/tmp-seed-test-accounts'
    | '/api/public/widget.js'
    | '/api/public/branding/$'
    | '/api/public/chat/config'
    | '/api/public/chat/escalate'
    | '/api/public/chat/feedback'
    | '/api/public/chat/message'
    | '/api/public/chat/poll'
    | '/api/public/chat/rate'
    | '/api/public/chat/session'
    | '/api/public/chat/upload'
    | '/api/public/hooks/sla-check'
    | '/api/public/staff-avatar/$'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  InviteRoute: typeof InviteRoute
  MfaRoute: typeof MfaRoute
  NoAccessRoute: typeof NoAccessRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  WidgetRoute: typeof WidgetRoute
  ApiPublicTmpSeedTestAccountsRoute: typeof ApiPublicTmpSeedTestAccountsRoute
  ApiPublicWidgetDotjsRoute: typeof ApiPublicWidgetDotjsRoute
  ApiPublicBrandingSplatRoute: typeof ApiPublicBrandingSplatRoute
  ApiPublicChatConfigRoute: typeof ApiPublicChatConfigRoute
  ApiPublicChatEscalateRoute: typeof ApiPublicChatEscalateRoute
  ApiPublicChatFeedbackRoute: typeof ApiPublicChatFeedbackRoute
  ApiPublicChatMessageRoute: typeof ApiPublicChatMessageRoute
  ApiPublicChatPollRoute: typeof ApiPublicChatPollRoute
  ApiPublicChatRateRoute: typeof ApiPublicChatRateRoute
  ApiPublicChatSessionRoute: typeof ApiPublicChatSessionRoute
  ApiPublicChatUploadRoute: typeof ApiPublicChatUploadRoute
  ApiPublicHooksSlaCheckRoute: typeof ApiPublicHooksSlaCheckRoute
  ApiPublicStaffAvatarSplatRoute: typeof ApiPublicStaffAvatarSplatRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/widget': {
      id: '/widget'
      path: '/widget'
      fullPath: '/widget'
      preLoaderRoute: typeof WidgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/no-access': {
      id: '/no-access'
      path: '/no-access'
      fullPath: '/no-access'
      preLoaderRoute: typeof NoAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mfa': {
      id: '/mfa'
      path: '/mfa'
      fullPath: '/mfa'
      preLoaderRoute: typeof MfaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/websites': {
      id: '/_authenticated/websites'
      path: '/websites'
      fullPath: '/websites'
      preLoaderRoute: typeof AuthenticatedWebsitesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/training': {
      id: '/_authenticated/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof AuthenticatedTrainingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/security': {
      id: '/_authenticated/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof AuthenticatedSecurityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/routing': {
      id: '/_authenticated/routing'
      path: '/routing'
      fullPath: '/routing'
      preLoaderRoute: typeof AuthenticatedRoutingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quality': {
      id: '/_authenticated/quality'
      path: '/quality'
      fullPath: '/quality'
      preLoaderRoute: typeof AuthenticatedQualityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/organizations': {
      id: '/_authenticated/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof AuthenticatedOrganizationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/knowledge': {
      id: '/_authenticated/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AuthenticatedKnowledgeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/intake': {
      id: '/_authenticated/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof AuthenticatedIntakeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inbox': {
      id: '/_authenticated/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthenticatedInboxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/departments': {
      id: '/_authenticated/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof AuthenticatedDepartmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contacts': {
      id: '/_authenticated/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthenticatedContactsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-console': {
      id: '/_authenticated/ai-console'
      path: '/ai-console'
      fullPath: '/ai-console'
      preLoaderRoute: typeof AuthenticatedAiConsoleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/widget.js': {
      id: '/api/public/widget.js'
      path: '/api/public/widget.js'
      fullPath: '/api/public/widget.js'
      preLoaderRoute: typeof ApiPublicWidgetDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tmp-seed-test-accounts': {
      id: '/api/public/tmp-seed-test-accounts'
      path: '/api/public/tmp-seed-test-accounts'
      fullPath: '/api/public/tmp-seed-test-accounts'
      preLoaderRoute: typeof ApiPublicTmpSeedTestAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/staff-avatar/$': {
      id: '/api/public/staff-avatar/$'
      path: '/api/public/staff-avatar/$'
      fullPath: '/api/public/staff-avatar/$'
      preLoaderRoute: typeof ApiPublicStaffAvatarSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sla-check': {
      id: '/api/public/hooks/sla-check'
      path: '/api/public/hooks/sla-check'
      fullPath: '/api/public/hooks/sla-check'
      preLoaderRoute: typeof ApiPublicHooksSlaCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/chat/upload': {
      id: '/api/public/chat/upload'
      path: '/api/public/chat/upload'
      fullPath: '/api/public/chat/upload'
      preLoaderRoute: typeof ApiPublicChatUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/chat/session': {
      id: '/api/public/chat/session'
      path: '/api/public/chat/session'
      fullPath: '/api/public/chat/session'
      preLoaderRoute: typeof ApiPublicChatSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/chat/rate': {
      id: '/api/public/chat/rate'
      path: '/api/public/chat/rate'
      fullPath: '/api/public/chat/rate'
      preLoaderRoute: typeof ApiPublicChatRateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/chat/poll': {
      id: '/api/public/chat/poll'
      path: '/api/public/chat/poll'
      fullPath: '/api/public/chat/poll'
      preLoaderRoute: typeof ApiPublicChatPollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/chat/message': {
      id: '/api/public/chat/message'
      path: '/api/public/chat/message'
      fullPath: '/api/public/chat/message'
      preLoaderRoute: typeof ApiPublicChatMessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/chat/feedback': {
      id: '/api/public/chat/feedback'
      path: '/api/public/chat/feedback'
      fullPath: '/api/public/chat/feedback'
      preLoaderRoute: typeof ApiPublicChatFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/chat/escalate': {
      id: '/api/public/chat/escalate'
      path: '/api/public/chat/escalate'
      fullPath: '/api/public/chat/escalate'
      preLoaderRoute: typeof ApiPublicChatEscalateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/chat/config': {
      id: '/api/public/chat/config'
      path: '/api/public/chat/config'
      fullPath: '/api/public/chat/config'
      preLoaderRoute: typeof ApiPublicChatConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/branding/$': {
      id: '/api/public/branding/$'
      path: '/api/public/branding/$'
      fullPath: '/api/public/branding/$'
      preLoaderRoute: typeof ApiPublicBrandingSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAiConsoleRoute: typeof AuthenticatedAiConsoleRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedContactsRoute: typeof AuthenticatedContactsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDepartmentsRoute: typeof AuthenticatedDepartmentsRoute
  AuthenticatedInboxRoute: typeof AuthenticatedInboxRoute
  AuthenticatedIntakeRoute: typeof AuthenticatedIntakeRoute
  AuthenticatedKnowledgeRoute: typeof AuthenticatedKnowledgeRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOrganizationsRoute: typeof AuthenticatedOrganizationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedQualityRoute: typeof AuthenticatedQualityRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedRoutingRoute: typeof AuthenticatedRoutingRoute
  AuthenticatedSecurityRoute: typeof AuthenticatedSecurityRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStaffRoute: typeof AuthenticatedStaffRoute
  AuthenticatedTrainingRoute: typeof AuthenticatedTrainingRoute
  AuthenticatedWebsitesRoute: typeof AuthenticatedWebsitesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAiConsoleRoute: AuthenticatedAiConsoleRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedContactsRoute: AuthenticatedContactsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDepartmentsRoute: AuthenticatedDepartmentsRoute,
  AuthenticatedInboxRoute: AuthenticatedInboxRoute,
  AuthenticatedIntakeRoute: AuthenticatedIntakeRoute,
  AuthenticatedKnowledgeRoute: AuthenticatedKnowledgeRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOrganizationsRoute: AuthenticatedOrganizationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedQualityRoute: AuthenticatedQualityRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedRoutingRoute: AuthenticatedRoutingRoute,
  AuthenticatedSecurityRoute: AuthenticatedSecurityRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStaffRoute: AuthenticatedStaffRoute,
  AuthenticatedTrainingRoute: AuthenticatedTrainingRoute,
  AuthenticatedWebsitesRoute: AuthenticatedWebsitesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  InviteRoute: InviteRoute,
  MfaRoute: MfaRoute,
  NoAccessRoute: NoAccessRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  WidgetRoute: WidgetRoute,
  ApiPublicTmpSeedTestAccountsRoute: ApiPublicTmpSeedTestAccountsRoute,
  ApiPublicWidgetDotjsRoute: ApiPublicWidgetDotjsRoute,
  ApiPublicBrandingSplatRoute: ApiPublicBrandingSplatRoute,
  ApiPublicChatConfigRoute: ApiPublicChatConfigRoute,
  ApiPublicChatEscalateRoute: ApiPublicChatEscalateRoute,
  ApiPublicChatFeedbackRoute: ApiPublicChatFeedbackRoute,
  ApiPublicChatMessageRoute: ApiPublicChatMessageRoute,
  ApiPublicChatPollRoute: ApiPublicChatPollRoute,
  ApiPublicChatRateRoute: ApiPublicChatRateRoute,
  ApiPublicChatSessionRoute: ApiPublicChatSessionRoute,
  ApiPublicChatUploadRoute: ApiPublicChatUploadRoute,
  ApiPublicHooksSlaCheckRoute: ApiPublicHooksSlaCheckRoute,
  ApiPublicStaffAvatarSplatRoute: ApiPublicStaffAvatarSplatRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
