/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WidgetRouteImport } from './routes/widget'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWebsitesRouteImport } from './routes/_authenticated/websites'
import { Route as AuthenticatedStaffRouteImport } from './routes/_authenticated/staff'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedOrganizationsRouteImport } from './routes/_authenticated/organizations'
import { Route as AuthenticatedKnowledgeRouteImport } from './routes/_authenticated/knowledge'
import { Route as AuthenticatedIntakeRouteImport } from './routes/_authenticated/intake'
import { Route as AuthenticatedInboxRouteImport } from './routes/_authenticated/inbox'
import { Route as ApiPublicWidgetDotjsRouteImport } from './routes/api/public/widget[.]js'
import { Route as ApiPublicChatPollRouteImport } from './routes/api/public/chat/poll'
import { Route as ApiPublicChatMessageRouteImport } from './routes/api/public/chat/message'
import { Route as ApiPublicChatFeedbackRouteImport } from './routes/api/public/chat/feedback'
import { Route as ApiPublicChatEscalateRouteImport } from './routes/api/public/chat/escalate'
import { Route as ApiPublicChatConfigRouteImport } from './routes/api/public/chat/config'

const WidgetRoute = WidgetRouteImport.update({
  id: '/widget',
  path: '/widget',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWebsitesRoute = AuthenticatedWebsitesRouteImport.update({
  id: '/websites',
  path: '/websites',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStaffRoute = AuthenticatedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrganizationsRoute =
  AuthenticatedOrganizationsRouteImport.update({
    id: '/organizations',
    path: '/organizations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKnowledgeRoute = AuthenticatedKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntakeRoute = AuthenticatedIntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInboxRoute = AuthenticatedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicWidgetDotjsRoute = ApiPublicWidgetDotjsRouteImport.update({
  id: '/api/public/widget.js',
  path: '/api/public/widget.js',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicChatPollRoute = ApiPublicChatPollRouteImport.update({
  id: '/api/public/chat/poll',
  path: '/api/public/chat/poll',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicChatMessageRoute = ApiPublicChatMessageRouteImport.update({
  id: '/api/public/chat/message',
  path: '/api/public/chat/message',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicChatFeedbackRoute = ApiPublicChatFeedbackRouteImport.update({
  id: '/api/public/chat/feedback',
  path: '/api/public/chat/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicChatEscalateRoute = ApiPublicChatEscalateRouteImport.update({
  id: '/api/public/chat/escalate',
  path: '/api/public/chat/escalate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicChatConfigRoute = ApiPublicChatConfigRouteImport.update({
  id: '/api/public/chat/config',
  path: '/api/public/chat/config',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/widget': typeof WidgetRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/intake': typeof AuthenticatedIntakeRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/organizations': typeof AuthenticatedOrganizationsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/websites': typeof AuthenticatedWebsitesRoute
  '/api/public/widget.js': typeof ApiPublicWidgetDotjsRoute
  '/api/public/chat/config': typeof ApiPublicChatConfigRoute
  '/api/public/chat/escalate': typeof ApiPublicChatEscalateRoute
  '/api/public/chat/feedback': typeof ApiPublicChatFeedbackRoute
  '/api/public/chat/message': typeof ApiPublicChatMessageRoute
  '/api/public/chat/poll': typeof ApiPublicChatPollRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/widget': typeof WidgetRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/intake': typeof AuthenticatedIntakeRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/organizations': typeof AuthenticatedOrganizationsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/websites': typeof AuthenticatedWebsitesRoute
  '/api/public/widget.js': typeof ApiPublicWidgetDotjsRoute
  '/api/public/chat/config': typeof ApiPublicChatConfigRoute
  '/api/public/chat/escalate': typeof ApiPublicChatEscalateRoute
  '/api/public/chat/feedback': typeof ApiPublicChatFeedbackRoute
  '/api/public/chat/message': typeof ApiPublicChatMessageRoute
  '/api/public/chat/poll': typeof ApiPublicChatPollRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/widget': typeof WidgetRoute
  '/_authenticated/inbox': typeof AuthenticatedInboxRoute
  '/_authenticated/intake': typeof AuthenticatedIntakeRoute
  '/_authenticated/knowledge': typeof AuthenticatedKnowledgeRoute
  '/_authenticated/organizations': typeof AuthenticatedOrganizationsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/staff': typeof AuthenticatedStaffRoute
  '/_authenticated/websites': typeof AuthenticatedWebsitesRoute
  '/api/public/widget.js': typeof ApiPublicWidgetDotjsRoute
  '/api/public/chat/config': typeof ApiPublicChatConfigRoute
  '/api/public/chat/escalate': typeof ApiPublicChatEscalateRoute
  '/api/public/chat/feedback': typeof ApiPublicChatFeedbackRoute
  '/api/public/chat/message': typeof ApiPublicChatMessageRoute
  '/api/public/chat/poll': typeof ApiPublicChatPollRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/widget'
    | '/inbox'
    | '/intake'
    | '/knowledge'
    | '/organizations'
    | '/reports'
    | '/staff'
    | '/websites'
    | '/api/public/widget.js'
    | '/api/public/chat/config'
    | '/api/public/chat/escalate'
    | '/api/public/chat/feedback'
    | '/api/public/chat/message'
    | '/api/public/chat/poll'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/widget'
    | '/inbox'
    | '/intake'
    | '/knowledge'
    | '/organizations'
    | '/reports'
    | '/staff'
    | '/websites'
    | '/api/public/widget.js'
    | '/api/public/chat/config'
    | '/api/public/chat/escalate'
    | '/api/public/chat/feedback'
    | '/api/public/chat/message'
    | '/api/public/chat/poll'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/widget'
    | '/_authenticated/inbox'
    | '/_authenticated/intake'
    | '/_authenticated/knowledge'
    | '/_authenticated/organizations'
    | '/_authenticated/reports'
    | '/_authenticated/staff'
    | '/_authenticated/websites'
    | '/api/public/widget.js'
    | '/api/public/chat/config'
    | '/api/public/chat/escalate'
    | '/api/public/chat/feedback'
    | '/api/public/chat/message'
    | '/api/public/chat/poll'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  WidgetRoute: typeof WidgetRoute
  ApiPublicWidgetDotjsRoute: typeof ApiPublicWidgetDotjsRoute
  ApiPublicChatConfigRoute: typeof ApiPublicChatConfigRoute
  ApiPublicChatEscalateRoute: typeof ApiPublicChatEscalateRoute
  ApiPublicChatFeedbackRoute: typeof ApiPublicChatFeedbackRoute
  ApiPublicChatMessageRoute: typeof ApiPublicChatMessageRoute
  ApiPublicChatPollRoute: typeof ApiPublicChatPollRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/widget': {
      id: '/widget'
      path: '/widget'
      fullPath: '/widget'
      preLoaderRoute: typeof WidgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/websites': {
      id: '/_authenticated/websites'
      path: '/websites'
      fullPath: '/websites'
      preLoaderRoute: typeof AuthenticatedWebsitesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/organizations': {
      id: '/_authenticated/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof AuthenticatedOrganizationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/knowledge': {
      id: '/_authenticated/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AuthenticatedKnowledgeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/intake': {
      id: '/_authenticated/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof AuthenticatedIntakeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inbox': {
      id: '/_authenticated/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthenticatedInboxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/widget.js': {
      id: '/api/public/widget.js'
      path: '/api/public/widget.js'
      fullPath: '/api/public/widget.js'
      preLoaderRoute: typeof ApiPublicWidgetDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/chat/poll': {
      id: '/api/public/chat/poll'
      path: '/api/public/chat/poll'
      fullPath: '/api/public/chat/poll'
      preLoaderRoute: typeof ApiPublicChatPollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/chat/message': {
      id: '/api/public/chat/message'
      path: '/api/public/chat/message'
      fullPath: '/api/public/chat/message'
      preLoaderRoute: typeof ApiPublicChatMessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/chat/feedback': {
      id: '/api/public/chat/feedback'
      path: '/api/public/chat/feedback'
      fullPath: '/api/public/chat/feedback'
      preLoaderRoute: typeof ApiPublicChatFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/chat/escalate': {
      id: '/api/public/chat/escalate'
      path: '/api/public/chat/escalate'
      fullPath: '/api/public/chat/escalate'
      preLoaderRoute: typeof ApiPublicChatEscalateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/chat/config': {
      id: '/api/public/chat/config'
      path: '/api/public/chat/config'
      fullPath: '/api/public/chat/config'
      preLoaderRoute: typeof ApiPublicChatConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedInboxRoute: typeof AuthenticatedInboxRoute
  AuthenticatedIntakeRoute: typeof AuthenticatedIntakeRoute
  AuthenticatedKnowledgeRoute: typeof AuthenticatedKnowledgeRoute
  AuthenticatedOrganizationsRoute: typeof AuthenticatedOrganizationsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedStaffRoute: typeof AuthenticatedStaffRoute
  AuthenticatedWebsitesRoute: typeof AuthenticatedWebsitesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedInboxRoute: AuthenticatedInboxRoute,
  AuthenticatedIntakeRoute: AuthenticatedIntakeRoute,
  AuthenticatedKnowledgeRoute: AuthenticatedKnowledgeRoute,
  AuthenticatedOrganizationsRoute: AuthenticatedOrganizationsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedStaffRoute: AuthenticatedStaffRoute,
  AuthenticatedWebsitesRoute: AuthenticatedWebsitesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  WidgetRoute: WidgetRoute,
  ApiPublicWidgetDotjsRoute: ApiPublicWidgetDotjsRoute,
  ApiPublicChatConfigRoute: ApiPublicChatConfigRoute,
  ApiPublicChatEscalateRoute: ApiPublicChatEscalateRoute,
  ApiPublicChatFeedbackRoute: ApiPublicChatFeedbackRoute,
  ApiPublicChatMessageRoute: ApiPublicChatMessageRoute,
  ApiPublicChatPollRoute: ApiPublicChatPollRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
