/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WidgetRouteImport } from './routes/widget'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicWidgetDotjsRouteImport } from './routes/api/public/widget[.]js'
import { Route as ApiPublicChatPollRouteImport } from './routes/api/public/chat/poll'
import { Route as ApiPublicChatMessageRouteImport } from './routes/api/public/chat/message'
import { Route as ApiPublicChatFeedbackRouteImport } from './routes/api/public/chat/feedback'
import { Route as ApiPublicChatEscalateRouteImport } from './routes/api/public/chat/escalate'
import { Route as ApiPublicChatConfigRouteImport } from './routes/api/public/chat/config'

const WidgetRoute = WidgetRouteImport.update({
  id: '/widget',
  path: '/widget',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWidgetDotjsRoute = ApiPublicWidgetDotjsRouteImport.update({
  id: '/api/public/widget.js',
  path: '/api/public/widget.js',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicChatPollRoute = ApiPublicChatPollRouteImport.update({
  id: '/api/public/chat/poll',
  path: '/api/public/chat/poll',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicChatMessageRoute = ApiPublicChatMessageRouteImport.update({
  id: '/api/public/chat/message',
  path: '/api/public/chat/message',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicChatFeedbackRoute = ApiPublicChatFeedbackRouteImport.update({
  id: '/api/public/chat/feedback',
  path: '/api/public/chat/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicChatEscalateRoute = ApiPublicChatEscalateRouteImport.update({
  id: '/api/public/chat/escalate',
  path: '/api/public/chat/escalate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicChatConfigRoute = ApiPublicChatConfigRouteImport.update({
  id: '/api/public/chat/config',
  path: '/api/public/chat/config',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/widget': typeof WidgetRoute
  '/api/public/widget.js': typeof ApiPublicWidgetDotjsRoute
  '/api/public/chat/config': typeof ApiPublicChatConfigRoute
  '/api/public/chat/escalate': typeof ApiPublicChatEscalateRoute
  '/api/public/chat/feedback': typeof ApiPublicChatFeedbackRoute
  '/api/public/chat/message': typeof ApiPublicChatMessageRoute
  '/api/public/chat/poll': typeof ApiPublicChatPollRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/widget': typeof WidgetRoute
  '/api/public/widget.js': typeof ApiPublicWidgetDotjsRoute
  '/api/public/chat/config': typeof ApiPublicChatConfigRoute
  '/api/public/chat/escalate': typeof ApiPublicChatEscalateRoute
  '/api/public/chat/feedback': typeof ApiPublicChatFeedbackRoute
  '/api/public/chat/message': typeof ApiPublicChatMessageRoute
  '/api/public/chat/poll': typeof ApiPublicChatPollRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/widget': typeof WidgetRoute
  '/api/public/widget.js': typeof ApiPublicWidgetDotjsRoute
  '/api/public/chat/config': typeof ApiPublicChatConfigRoute
  '/api/public/chat/escalate': typeof ApiPublicChatEscalateRoute
  '/api/public/chat/feedback': typeof ApiPublicChatFeedbackRoute
  '/api/public/chat/message': typeof ApiPublicChatMessageRoute
  '/api/public/chat/poll': typeof ApiPublicChatPollRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/widget'
    | '/api/public/widget.js'
    | '/api/public/chat/config'
    | '/api/public/chat/escalate'
    | '/api/public/chat/feedback'
    | '/api/public/chat/message'
    | '/api/public/chat/poll'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/widget'
    | '/api/public/widget.js'
    | '/api/public/chat/config'
    | '/api/public/chat/escalate'
    | '/api/public/chat/feedback'
    | '/api/public/chat/message'
    | '/api/public/chat/poll'
  id:
    | '__root__'
    | '/'
    | '/widget'
    | '/api/public/widget.js'
    | '/api/public/chat/config'
    | '/api/public/chat/escalate'
    | '/api/public/chat/feedback'
    | '/api/public/chat/message'
    | '/api/public/chat/poll'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WidgetRoute: typeof WidgetRoute
  ApiPublicWidgetDotjsRoute: typeof ApiPublicWidgetDotjsRoute
  ApiPublicChatConfigRoute: typeof ApiPublicChatConfigRoute
  ApiPublicChatEscalateRoute: typeof ApiPublicChatEscalateRoute
  ApiPublicChatFeedbackRoute: typeof ApiPublicChatFeedbackRoute
  ApiPublicChatMessageRoute: typeof ApiPublicChatMessageRoute
  ApiPublicChatPollRoute: typeof ApiPublicChatPollRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/widget': {
      id: '/widget'
      path: '/widget'
      fullPath: '/widget'
      preLoaderRoute: typeof WidgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/widget.js': {
      id: '/api/public/widget.js'
      path: '/api/public/widget.js'
      fullPath: '/api/public/widget.js'
      preLoaderRoute: typeof ApiPublicWidgetDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/chat/poll': {
      id: '/api/public/chat/poll'
      path: '/api/public/chat/poll'
      fullPath: '/api/public/chat/poll'
      preLoaderRoute: typeof ApiPublicChatPollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/chat/message': {
      id: '/api/public/chat/message'
      path: '/api/public/chat/message'
      fullPath: '/api/public/chat/message'
      preLoaderRoute: typeof ApiPublicChatMessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/chat/feedback': {
      id: '/api/public/chat/feedback'
      path: '/api/public/chat/feedback'
      fullPath: '/api/public/chat/feedback'
      preLoaderRoute: typeof ApiPublicChatFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/chat/escalate': {
      id: '/api/public/chat/escalate'
      path: '/api/public/chat/escalate'
      fullPath: '/api/public/chat/escalate'
      preLoaderRoute: typeof ApiPublicChatEscalateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/chat/config': {
      id: '/api/public/chat/config'
      path: '/api/public/chat/config'
      fullPath: '/api/public/chat/config'
      preLoaderRoute: typeof ApiPublicChatConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WidgetRoute: WidgetRoute,
  ApiPublicWidgetDotjsRoute: ApiPublicWidgetDotjsRoute,
  ApiPublicChatConfigRoute: ApiPublicChatConfigRoute,
  ApiPublicChatEscalateRoute: ApiPublicChatEscalateRoute,
  ApiPublicChatFeedbackRoute: ApiPublicChatFeedbackRoute,
  ApiPublicChatMessageRoute: ApiPublicChatMessageRoute,
  ApiPublicChatPollRoute: ApiPublicChatPollRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
